export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';

export const GET_DOCUMENT = 'GET_DOCUMENT';
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS';

export const PROCESSING = 'PROCESSING';

export const REQUEST_ERROR = 'REQUEST_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const SET_AUTH = 'SET_AUTH';

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const CHANGE_USER_PASS = "CHANGE_USER_PASS";
export const CHANGE_USER_PASS_SUCCESS = "CHANGE_USER_PASS_SUCCESS";

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_NEW = 'GET_NEW';
export const GET_NEW_SUCCESS = 'GET_NEW_SUCCESS';

export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';

export const SET_ENROLLMENT = 'SET_ENROLLMENT';
export const SET_ENROLLMENT_SUCCESS = 'SET_ENROLLMENT_SUCCESS';

export const SET_COMPLAINT = 'SET_COMPLAINT';
export const SET_COMPLAINT_SUCCESS = 'SET_COMPLAINT_SUCCESS';

export const GET_COMPLAINTS = 'GET_COMPLAINTS';
export const GET_COMPLAINTS_SUCCESS = 'GET_COMPLAINTS_SUCCESS';

export const GET_COMPLAINT_IMAGES_SUCCESS = 'GET_COMPLAINT_IMAGES_SUCCESS';

export const GET_ALERTS = 'GET_ALERTS';
export const GET_ALERTS_SUCCESS = 'GET_ALERTS_SUCCESS';

export const SET_ALERT = 'SET_ALERT';
export const SET_ALERT_SUCCESS = 'SET_ALERT_SUCCESS';

export const GET_INFORMATION = 'GET_INFORMATION';
export const GET_INFORMATION_SUCCESS = 'GET_INFO_SUCCESS';
