export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';

export const GET_DOCUMENT = 'GET_DOCUMENT';
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS';

export const PROCESSING = 'PROCESSING';

export const REQUEST_ERROR = 'REQUEST_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const SET_AUTH = 'SET_AUTH';

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_NEW = 'GET_NEW';
export const GET_NEW_SUCCESS = 'GET_NEW_SUCCESS';

export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';

export const SET_ENROLLMENT = 'SET_ENROLLMENT';
export const SET_ENROLLMENT_SUCCESS = 'SET_ENROLLMENT_SUCCESS';
