export const defaultProfile = {
  username: '',
  firstname: '',
  lastname: '',
  mail: '',
  phonenumber: '',
  city: '',
  tasks: '',
  nationality: '',
  cuit: '',
  dni: '',
  address: '',
  postalcode: '',
  province: '',
  country: '',
  birthdate: null,
  companies: [],
};
